apiVersion: apps/v1
kind: Deployment
metadata:
  name: elliott-and-mycah
spec:
  selector:
    matchLabels:
      app: elliott-and-mycah
  replicas: 3
  template:
    metadata:
      labels:
        app: elliott-and-mycah
    spec:
      containers:
        - name: elliott-and-mycah
          image: registry.digitalocean.com/mantocko/elliott-and-mycah
          resources:
            requests:
              memory: "25Mi"
              cpu: "25m"
            limits:
              memory: "100Mi"
              cpu: "100m"
          ports:
            - containerPort: 80
